2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_setup.py:_flush():76] Current SDK version is 0.16.4
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_setup.py:_flush():76] Configure stats pid to 7110
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_setup.py:_flush():76] Loading settings from /home/srihari/.config/wandb/settings
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_setup.py:_flush():76] Loading settings from /home/srihari/SEM6/CV/CV_A2/wandb/settings
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_init.py:_log_setup():526] Logging user logs to /home/srihari/SEM6/CV/CV_A2/wandb/run-20240319_200853-h968gwc9/logs/debug.log
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_init.py:_log_setup():527] Logging internal logs to /home/srihari/SEM6/CV/CV_A2/wandb/run-20240319_200853-h968gwc9/logs/debug-internal.log
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x74ea5252bb10>
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_init.py:init():566] calling init triggers
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_init.py:init():616] starting backend
2024-03-19 20:08:53,073 INFO    MainThread:7110 [wandb_init.py:init():620] setting up manager
2024-03-19 20:08:53,074 INFO    MainThread:7110 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-19 20:08:53,074 INFO    MainThread:7110 [wandb_init.py:init():628] backend started and connected
2024-03-19 20:08:53,080 INFO    MainThread:7110 [wandb_run.py:_label_probe_notebook():1295] probe notebook
2024-03-19 20:08:53,085 INFO    MainThread:7110 [wandb_init.py:init():720] updated telemetry
2024-03-19 20:08:53,089 INFO    MainThread:7110 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-19 20:17:52,373 ERROR   MainThread:7110 [wandb_init.py:init():779] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-03-19 20:17:54,388 ERROR   MainThread:7110 [wandb_init.py:init():1194] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/home/srihari/miniconda3/envs/conda_cv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/srihari/miniconda3/envs/conda_cv/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
